apiVersion: v1
kind: Service
metadata:
  name: eks-cicd-demo-service
  labels:
    app: eks-cicd-demo 

spec:
  type: LoadBalancer
  selector:
    app: eks-cicd-demo # maps to the pod which have the label as eks-cicd-dem
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 #container port
      